### ISSUE TITLE
ShelvesetComparer won't install on VS 2017 Enterprise

### ISSUE THREAD

**Issue by valeriejm** [hamidshahid/shelvesetcomparer#5]
It says the supported product is:
7/2/2019 10:56:39 AM - 		Microsoft.VisualStudio.Pro

And my product is:
7/2/2019 10:56:39 AM - Found installed product - Visual Studio Enterprise 2017

And I get this error:
7/2/2019 10:56:39 AM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.

Below is the complete text.
Is there a non-free version I need to use with the Enterprise product? If so, how do I get it?

7/2/2019 10:56:38 AM - Microsoft VSIX Installer
7/2/2019 10:56:38 AM - -------------------------------------------
7/2/2019 10:56:38 AM - vsixinstaller.exe version:
7/2/2019 10:56:38 AM - 15.9.3041
7/2/2019 10:56:38 AM - -------------------------------------------
7/2/2019 10:56:38 AM - Command line parameters:
7/2/2019 10:56:38 AM - C:\program files (x86)\microsoft visual studio\installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\u0134059\Downloads\ShelvesetComparer.vsix
7/2/2019 10:56:38 AM - -------------------------------------------
7/2/2019 10:56:38 AM - Microsoft VSIX Installer
7/2/2019 10:56:38 AM - -------------------------------------------
7/2/2019 10:56:39 AM - Initializing Install...
7/2/2019 10:56:39 AM - Extension Details...
7/2/2019 10:56:39 AM - 	Identifier         : 50f4bcb5-060b-4090-93c5-30d3260ddc8c
7/2/2019 10:56:39 AM - 	Name               : ShelvesetComparer
7/2/2019 10:56:39 AM - 	Author             : Hamid Shahid
7/2/2019 10:56:39 AM - 	Version            : 1.5.0.0
7/2/2019 10:56:39 AM - 	Description        : The extension allows you to compare files in two shelvesets.
7/2/2019 10:56:39 AM - 	Locale             : en-US
7/2/2019 10:56:39 AM - 	MoreInfoURL        : http://visualstudiogallery.msdn.microsoft.com/1fa59764-efc6-457a-a5f3-81ca68e280e8
7/2/2019 10:56:39 AM - 	InstalledByMSI     : False
7/2/2019 10:56:39 AM - 	SupportedFrameworkVersionRange : [4.5,)
7/2/2019 10:56:39 AM - 
7/2/2019 10:56:39 AM - 	SignatureState     : Unsigned
7/2/2019 10:56:39 AM - 	Supported Products : 
7/2/2019 10:56:39 AM - 		Microsoft.VisualStudio.Pro
7/2/2019 10:56:39 AM - 			Version : [12.0]
7/2/2019 10:56:39 AM - 
7/2/2019 10:56:39 AM - 	References         : 
7/2/2019 10:56:39 AM - Signature Details...
7/2/2019 10:56:39 AM - 	Extension is not signed.
7/2/2019 10:56:39 AM - 
7/2/2019 10:56:39 AM - Searching for applicable products...
7/2/2019 10:56:39 AM - Found installed product - Microsoft Visual Studio 2013 Shell (Integrated)
7/2/2019 10:56:39 AM - Found installed product - Global Location
7/2/2019 10:56:39 AM - Found installed product - Visual Studio Enterprise 2017
7/2/2019 10:56:39 AM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

**Comment by valeriejm** [comment]
Never mind. Looks like I downloaded an earlier version that did not support VS 2017. Not sure how I got that version.
